import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import db from "@/db/indexedDB";
import { format } from "date-fns";

export async function generateHealthReport(patientName: string = "Bala") {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const medications = await db.medications.toArray();
  const logs = await db.logs.toArray();
  const today = format(new Date(), "MMMM do, yyyy");
  const reportDate = format(new Date(), "yyyy-MM-dd HH:mm");

  // ====== HEADER ======
  doc.setFillColor(26, 28, 28);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(57, 255, 20);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("DR. B-MAX", 14, 18);

  doc.setTextColor(180, 203, 206);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("MEDICAL COMPANION — HEALTH REPORT", 14, 26);
  doc.text(`Generated: ${reportDate}`, 14, 33);

  // Patient info box
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Patient: ${patientName}`, 120, 18);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Report Date: ${today}`, 120, 26);

  // ====== SUMMARY ======
  doc.setTextColor(26, 28, 28);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Medication Summary", 14, 52);

  const takenCount = logs.filter(l => l.status === "Taken").length;
  const missedCount = logs.filter(l => l.status === "Missed").length;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(66, 72, 73);
  doc.text(`Total Prescriptions: ${medications.length}`, 14, 60);
  doc.text(`Doses Taken: ${takenCount}`, 14, 66);
  doc.text(`Doses Missed: ${missedCount}`, 14, 72);
  const adherence = takenCount + missedCount > 0
    ? Math.round((takenCount / (takenCount + missedCount)) * 100)
    : 100;
  doc.text(`Adherence Rate: ${adherence}%`, 14, 78);

  // Adherence bar
  doc.setFillColor(220, 220, 220);
  doc.roundedRect(14, 82, 120, 6, 2, 2, "F");
  doc.setFillColor(57, 255, 20);
  doc.roundedRect(14, 82, 120 * (adherence / 100), 6, 2, 2, "F");

  // ====== MEDICATIONS TABLE ======
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 28, 28);
  doc.text("Active Prescriptions", 14, 100);

  const tableData = medications.map(med => [
    med.name,
    med.dosage || "As directed",
    med.time,
    med.durationDays ? `${med.durationDays} days` : "Ongoing",
    `${med.inventory} pills`,
    med.startDate || "N/A",
    med.instructions || "—",
  ]);

  autoTable(doc, {
    startY: 104,
    head: [["Medication", "Dosage", "Time", "Duration", "Inventory", "Start Date", "Instructions"]],
    body: tableData,
    headStyles: {
      fillColor: [26, 28, 28],
      textColor: [57, 255, 20],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 8, textColor: [26, 28, 28] },
    alternateRowStyles: { fillColor: [240, 244, 245] },
    margin: { left: 14, right: 14 },
  });

  // ====== HISTORY TABLE ======
  const finalY = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 150;
  
  if (logs.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 28, 28);
    doc.text("Recent Dose History", 14, finalY + 14);

    const recentLogs = logs.slice(-20).reverse();
    const historyData = await Promise.all(recentLogs.map(async log => {
      const med = await db.medications.get(log.medicationId);
      return [
        med?.name || `ID: ${log.medicationId}`,
        log.date,
        log.status,
        format(new Date(log.timestamp), "h:mm a"),
      ];
    }));

    autoTable(doc, {
      startY: finalY + 18,
      head: [["Medication", "Date", "Status", "Time"]],
      body: historyData,
      headStyles: { fillColor: [66, 72, 73], textColor: [255, 255, 255], fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      didDrawCell: (data) => {
        if (data.column.index === 2 && data.cell.raw === "Missed" && data.section === "body") {
          doc.setTextColor(255, 49, 49);
        }
      },
      margin: { left: 14, right: 14 },
    });
  }

  // ====== FOOTER ======
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Generated by Dr. B-MAX Medical Companion — Offline & Private",
      14, 290
    );
    doc.text(`Page ${i} of ${pageCount}`, 180, 290);
  }

  doc.save(`DrBMax_HealthReport_${format(new Date(), "yyyyMMdd")}.pdf`);
}
